excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- NewYorkTimesTests
- NewYorkTimesUITests
identifier_name:
 allowed_symbols: ["_"] # these are allowed in type names
